version: '3'

services:
  orbitdb:
    build: 
      context: .
    container_name: orbitdb-container
    ports:
      - "3000:3000" # Adjust port mapping as needed
    volumes:
      - .:/app # Mount your code directory into the container
    environment:
      - NODE_ENV=production

